// <auto-generated />
using ManterClasseObj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManterClasseObj.Migrations
{
    [DbContext(typeof(ManterClasseObjContext))]
    [Migration("20220317172816_atual")]
    partial class atual
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ManterClasseObj.Model.ClasseRicardo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClasseRicardo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "entidade (Empresa, órgão)"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "departamento"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "obra"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Descricao = "serviços"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Descricao = "processo"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Descricao = "política pública"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Descricao = "sistema de informações"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            Descricao = "procedimento"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Descricao = "controle"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            Descricao = "demonstrativo"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            Descricao = "itens de orçamento"
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            Descricao = "normativo"
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            Descricao = "folha de pagamento"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
